# Add divergent country names here as they show up in data!
known_country_names = {
    "Afghanistan": ["Afghanistan, Islamic Rep. of"],
    "Andorra": ["AndorrA", "Andorra, Principality of", "Andorra, Principality of ", "Andorra, Principality of  "],
    "Antigua & Barbuda": ["Antigua Barbuda", "Antigua and Barbuda", "Antigua  Barbuda"],
    "Armenia": ["Armenia, Rep. of"],
    "Aruba": ["Aruba, Kingdom of the Netherlands"],
    "Azerbaijan": ["Azerbaijan, Rep. of"],
    "Bahamas": ["Bahamas, the", "Bahamas The", "Bahamas, The"],
    "Bahrain": ["Bahrain, Kingdom of"],
    "Belarus": ["Belarus, Rep. of"],
    "Bosnia & Herzegovina": ["Bosnia and Herzegovina", "Bosnia Herzegovina", "Bosnia  Herzegovina"],
    "Brunei": ["Brunei Darussalam"],
    "Cape Verde": ["Cabo Verde"],
    "Central African Republic": ["Central African Rep."],
    "China": ["China Peoples Republic of", "China, People's Republic of", "China, P.R.: Mainland"],
    "Comoros": ["Comoros, Union of the"],
    "Congo (DRC)": ["Congo, The Democratic Republic of the", "DRC", "Congo Dem Rep of the", "Congo, Dem. Rep. of the"],
    "Congo (Republic of)": ["Congo", "Congo-Brazzaville", "Congo Brazzaville", "Congo Republic of", "Congo, Republic of ", "Congo, Rep. of"],
    "Cote d'Ivoire": ["Côte d'Ivoire", "Ivory Coast", "Cote dIvoire", "C\u00f4te d`Ivoire", "Côte d ́Ivoire"],
    "Croatia": ["Croatia, Rep. of"],
    "Czech Republic": ["Czech Rep.", "Czechia", "Check Republic"],
    "Dominican Republic": ["Dominican Rep."],
    "East Timor": ["TimorLeste", "Timor-Leste"],
    "Egypt": ["Egypt, Arab Rep. of"],
    "Equatorial Guinea": ["Equatorial Guinea, Rep. of"],
    "Eritrea": ["Eritrea, The State of"],
    "Estonia": ["Estonia, Rep. of"],
    "Eswatini (Swaziland)": ["Eswatini", "Swaziland", "Eswatini Swaziland", "Eswatini, Kingdom of"],
    "Ethiopia": ["Ethiopia, The Federal Dem. Rep. of"],
    "French Guiana": ["Guiana, French"],
    "Fiji": ["Fiji, Rep. of"],
    "Gambia": ["Gambia", "Gambia, the", "Gambia The", "Gambia, The", "The Gambia"],
    "Guinea Bissau": ["GuineaBissau", "Guinea Bissau"],
    "Guyana": ["Guayana"],
    "Hong Kong": ["Hong Kong SAR", "China, P.R.: Hong Kong"],
    "Iran": ["Iran, Islamic Rep. of"],
    "Kazakhstan": ["Kazakhstan, Rep. of"],
    "Kyrgiztan": ["Kyrgyz Republic", "Kyrgyz Rep"],
    "Lao": ["Lao PDR", "Lao P.D.R.", "Lao P.D.R. ", "Lao People's Dem. Rep"],
    "Lesotho": ["Lesotho, Kingdom of"],
    "Libya": ["Libyan Arab Jamahiriya", "Lybia"],
    "Macao": ["Macao SAR", "China, P.R.: Macao"],
    "Madagascar": ["Madagascar, Rep. of"],
    "Marshall Islands": ["Marshall Islands, Rep. of the"],
    "Mauritania": ["Mauritania, Islamic Rep. of"],
    "Micronesia": ["Micronesia Fed States of", "Micronesia, Fed. States of", "Micronesia, Federated States of"],
    "Moldova": ["Moldova, Rep. of"],
    "Mozambique": ["Mozambique, Rep. of"],
    "Nauru": ["Nauru, Rep. of"],
    "Netherlands": ["Netherlands, The"],
    "North Korea": ["Korea, Dem. People's Rep. of"],
    "North Macedonia": ["Macedonia", "Macedonia, The Former Yugoslav Republic of", "North Macedonia ", "North Macedonia, Republic of", "North Macedonia, Republic of "],
    "Palau": ["Palau, Rep. of"],
    "Palestine": ["West Bank and Gaza"],
    "Pitcairn Islands": ["Pitcairn Islands"],
    "Poland": ["Poland, Rep. of"],
    "Reunion": ["Réunion"],
    "Russia": ["Russian Federation"],
    "San Marino": ["San Marino, Rep. of"],
    "Sao Tome and Principe": ["São Tomé and Príncipe", "São Tomé and Príncipe ", "São Tomé and Príncipe, Dem. Rep. of"],
    "Serbia": ["Serbia, Rep. of"],
    "Serbia and Montenegro": ["Montenegro"],
    "Slovakia": ["Slovak Republic", "Slovak Rep"],
    "Slovenia": ["Slovenia, Rep. of"],
    "South Korea": ["Korea Republic of", "Korea, Republic of", "Korea, Rep. of"],
    "South Sudan": ["South Sudan Republic of", "South Sudan, Republic of", "South Sudan, Rep. of"],
    "St. Kitts & Nevis": ["St. Kitts and Nevis"],
    "St. Lucia": ["St. Lucia"],
    "St. Vincent & the Grenadines": ["St. Vincent and the Grenadines"],
    "Syria": ["Syrian Arab Rep", "Syrian Arab Rep."],
    "Taiwan": ["Taiwan Province of China"],
    "Tajikistan": ["Tajikistan, Rep. of"],
    "Tanzania": ["Tanzania, United Rep. of"],
    "Timor-Leste": ["Timor-Leste, Dem. Rep. of"],
    "Turkey": ["Turkiye Republic of", "Türkiye, Republic of", "Türkiye, Rep. of"],
    "Uruguay": ["Republica Oriental del Uruguay", "República Oriental del Uruguay"],
    "US Virgin Islands": ["United States Virgin Islands"],
    "Uzbekistan": ["Uzbekistan, Rep. of"],
    "Vatican": ["Holy See", "Vatican City"],
    "Venezuela": ["Venezuela, Rep. Bolivariana de"],
    "Viet Nam": ["Vietnam"],
    "Wallis & Futuna Islands": ["Wallis and Futuna Islands"],
    "Yemen": ["Yemen, Rep. of", "Yemen, Rep."],
}

# Montenegro ????? what to do with these two?
# Serbia

# South Sudan is not in all_countries_in_the_world list!
# Kyrgiztan is not in all_countries_in_the_world list!
# Bosnia Herzegovina is not in all_countries_in_the_world list!
# Guinea Bissau is not in all_countries_in_the_world list!
#	Kosovo is not in all_countries_in_the_world list!
